server:
  port: 9002
spring:
  application:
    name: nacos-dubbo-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #配置Nacos地址
management:
  endpoints:
    web:
      exposure:
        include: '*'
dubbo:
  registry:
    address: nacos://127.0.0.1:8848/?username=nacos&password=nacos
  scan:
    base-packages: com.jmy.provider
  protocol:
    name: dubbo
    port: -1
  application:
    name: nacos-dubbo-provider