server:
  port: 8001

spring:
  application:
    name: nacos-dubbo-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #配置Nacos地址
management:
  endpoints:
    web:
      exposure:
        include: '*'
dubbo:
  registry:
    address: nacos://${spring.cloud.nacos.discovery.server-addr}/?username=nacos&password=nacos
  scan:
    base-packages: com.jmy.consumer
  protocol:
    name: dubbo
    port: -1
  application:
    name: ${spring.application.name}